### ISSUE TITLE
SR 2.7

### ISSUE THREAD

**Issue by cryham** [flathub/org.tuxfamily.StuntRally#11]
Hi @AsciiWolf could you please update flatpak to latest SR version 2.7, tagged recenty?

**Comment by AsciiWolf** [comment]
Hi, sure, it is on my TODO list and I plan to do it over this weekend. :-)

There are still some minor issues though (see https://github.com/stuntrally/stuntrally/issues/67#issuecomment-1305489138).

**Comment by cryham** [comment]
Cool. Yes, I replied in https://github.com/stuntrally/stuntrally/issues/31 (won't fix in old SR)

**Comment by AsciiWolf** [comment]
@cryham By the way, there is a small typo on [the downloads page](https://stuntrally.tuxfamily.org/downloads). I think that there should be November instead of October in the release date. :-)

**Comment by AsciiWolf** [comment]
I have updated #7 and will merge the PR once it is tested. :-)

**Comment by cryham** [comment]
Ah thanks, fixed.

**Comment by cryham** [comment]
So is it done? Is it on this url?
https://flathub.org/apps/details/org.tuxfamily.StuntRally
I see 2.6.1 on that page, also old SR info etc.

**Comment by AsciiWolf** [comment]
The new build was committed for publishing. It will be available in a few hours. :-)

**Comment by AsciiWolf** [comment]
Regarding the old SR info, it is taken [from here](https://github.com/flathub/org.tuxfamily.StuntRally/blob/master/org.tuxfamily.StuntRally.appdata.xml#L9) and I forgot to update it. Could you please tell me what is the correct amount of tracks/sceneries, cars/motorbikes/etc. and other changes so I can update it? Thanks!

**Comment by cryham** [comment]
Ok. You can just copy from [SR homepage](https://stuntrally.tuxfamily.org/):

It features a rich variety of 202 [tracks](https://stuntrally.tuxfamily.org/tracks) in 37 sceneries also on other planets.

Track difficulty ranges from short and easy to very difficult stunt tracks
including jumps, skewed loops, pipes winding in 3D, obstacles or all at once.

The 25 [vehicles](https://stuntrally.tuxfamily.org/cars) include: 11 regular cars, 6 extreme (with bigger wheels), 2 motorbikes, an 8 wheeled bus, 1 old truck, 3 hovering spaceships and 1 bouncing sphere.

**Comment by AsciiWolf** [comment]
Thanks! I will update the appdata file. :-)

**Comment by AsciiWolf** [comment]
#13

**Comment by cryham** [comment]
Great, thank you.
I tested and it's okay. I only saw that R,G,B colors are switched on MyGui texts (I'm guessing it's different version than mine/recent or something) e.g. Vehicle tab and damage is normally Red not blue, but whatever not a big issue.

**Comment by cryham** [comment]
BTW also SR icon has changed to this: https://github.com/stuntrally/stuntrally/blob/master/data/gui/stuntrally.png

**Comment by AsciiWolf** [comment]
The swapped RGB colors were mentioned [here](https://github.com/flathub/org.tuxfamily.StuntRally/pull/7#issuecomment-1312577751), however there's not much I can do on my side to fix it in the Flatpak (without patching the game code) and I consider it being a quite minor issue.

The game icon is already updated, however it will take some time for the Flathub web store to display the updated icon. GNOME Software and KDE Discover on my desktop both already display the new icon.
